server:
  http_listen_address: 0.0.0.0
  http_listen_port: $PORT_PROMTAIL

positions:
  filename: /tmp/positions.yaml

clients:
  - url: $PROMTAIL_URL

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: $PROMTAIL_NAME
  static_configs:
  - targets:
      - localhost
    labels:
      job: $PROMTAIL_LABEL
      __path__: /var/lib/docker/containers/*/*log
  # --log-opt tag="{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
  pipeline_stages:
  - json:
      expressions:
        output: log
        stream: stream
        attrs:
  - json:
      expressions:
        tag:
      source: attrs
  - regex:
      expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
      source: tag
  - labels:
      # tag:
      stream:
      container_name:
  - output:
      source: output