{
 "title": "API Gateway",
 "description": "Visualize AWS API Gateway metrics",
 "tags": [
  "cloudwatch",
  "support",
  "api-gateway"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   {
    "name": "agg",
    "label": "Aggregation",
    "query": "1s,5s,10s,30s,1m,5m,15m,1h,6h,1d,7d,30d"
   },
   { "name": "region", "label": "Region", "query": "us-east-1" },
   {
    "name": "apiname",
    "label": "ApiName",
    "query": "dimension_values($region,AWS/ApiGateway,Count,ApiName)"
   },
   {
    "name": "stage",
    "label": "AND Stage",
    "query": "dimension_values($region,AWS/ApiGateway,Count,Stage, {\"ApiName\": \"$apiname\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Count",
     "namespace": "AWS/ApiGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Latency / IntegrationLatency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "IntegrationLatency",
     "namespace": "AWS/ApiGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "4XXError / 5XXError",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "id": "e400",
     "item": { "filter": "" },
     "metricName": "4XXError",
     "namespace": "AWS/ApiGateway",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "id": "e500",
     "item": { "filter": "" },
     "metricName": "5XXError",
     "namespace": "AWS/ApiGateway",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "Total Error Rate",
     "application": { "filter": "" },
     "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
     "expression": "SUM([e400,e500])*100/countt",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "id": "rate",
     "item": { "filter": "" },
     "metricEditorMode": 1,
     "metricName": "Count",
     "namespace": "AWS/ApiGateway",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "CacheHitCount / CacheMissCount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CacheHitCount",
     "namespace": "AWS/ApiGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CacheMissCount",
     "namespace": "AWS/ApiGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 28 },
   "options": {
    "content": "<a href=\"http://www.monitoringartist.com\" target=\"_blank\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-metrics-and-dimensions.html\">AWS CloudWatch API Gateway documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/dashboards/1516\">Installed from Grafana.com dashboards</a>"
   }
  }
 ]
}