{
 "title": "Log Monitoring",
 "tags": [
  "docker",
  "logs",
  "support"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "Production : prod, QA : qa, Dev : dev"
   },
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$env-(.*)\"},job)"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(container_last_seen{job=~\"(.*)$group(.*)\"},container_label_com_docker_swarm_service_name)\n"
    }
   },
   {
    "name": "container_name",
    "label": "Container",
    "query": {
     "query": "label_values(container_last_seen{container_label_com_docker_swarm_service_name=~\"$service\"}, name)"
    }
   },
   { "name": "stream", "label": "Stream", "query": "label_values(stream)" },
   { "name": "searchable_pattern", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=~\"$container_name\",stream=~\"$stream\"}|~ \"(?i)$searchable_pattern\" )[$__interval]))"
    }
   ]
  },
  {
   "title": "Errors by Conainer",
   "type": "bargauge",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=~\"$container_name\",stream=\"stderr\"}|~ \"(?i)$searchable_pattern\" )[$__interval])) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=~\"$container_name\",stream=\"stderr\"}|~ \"(?i)$searchable_pattern\" )[$__interval]))"
    }
   ]
  },
  {
   "title": "Log Streams",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=~\"$container_name\"}|~ \"(?i)$searchable_pattern\" )[$__interval])) by (stream)",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time(({container_name=~\"$container_name\",stream=\"stderr\"}|~ \"(?i)$searchable_pattern\" )[$__interval]))) / (sum(count_over_time(({container_name=~\"$container_name\"}|~ \"(?i)$searchable_pattern\" )[$__interval])))"
    }
   ]
  },
  {
   "title": " Live logs",
   "type": "logs",
   "description": "Live logs ",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{container_name=~\"$container_name\", stream=~\"$stream\"} |~ \"(?i)$searchable_pattern\" "
    }
   ]
  }
 ]
}