{
 "title": "Environment Explorer",
 "tags": [
  "servers",
  "support"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "env",
    "label": "Environment",
    "query": "Production : prod, QA : qa, Dev : dev"
   },
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$env-(.*)\"},job)"
    }
   },
   {
    "name": "job",
    "label": "Node Export",
    "query": {
     "query": "label_values(node_uname_info{job=~\"(.*)-$group-(.*)\"},job)"
    }
   },
   {
    "name": "cadvisor",
    "label": "cAdvisor",
    "query": {
     "query": "label_values(cadvisor_version_info{job=~\"(.*)-$group-(.*)\"},job)"
    }
   },
   {
    "name": "maxmount",
    "label": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Target Nodes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "10" }
   ]
  },
  {
   "title": "RAM",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc((1 - (node_memory_MemAvailable_bytes{job=~\"$job\"} / (node_memory_MemTotal_bytes{job=~\"$job\"})))* 100)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(100-(avg(rate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\"}[$interval])) by (job) * 100))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Root Directory",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc((node_filesystem_size_bytes{job=~\"$job\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {job=~\"$job\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sort_desc((1 - (node_memory_MemAvailable_bytes{job=~\"$job\"} / (node_memory_MemTotal_bytes{job=~\"$job\"})))* 100)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=~\"$job\",mode='system'}) by (job))"
    }
   ]
  },
  {
   "title": "Stacks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(container_memory_rss{job=~\"$cadvisor\",container_label_com_docker_swarm_task_name=~\".+\"}) by (container_label_com_docker_stack_namespace))\r\n"
    }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(container_memory_rss{job=~\"$cadvisor\",container_label_com_docker_swarm_task_name=~\".+\"}) by (container_label_com_docker_swarm_service_name))\r\n"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{job=~\"$cadvisor\",name=~\".+\"}[300s]))"
    }
   ]
  },
  {
   "title": "File Systems (EXT/XFS)",
   "type": "table",
   "description": "In this kanban: the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=~\"$job\",fstype=~\"ext.*|xfs|lustre\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes {job=~\"$job\",fstype=~\"ext.*|xfs|lustre\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "sort_desc((node_filesystem_size_bytes{job=~\"$job\",fstype=~\"ext.*|xfs|lustre\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.*|xfs|lustre\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {job=~\"$job\",fstype=~\"ext.*|xfs|lustre\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"ext.*|xfs|lustre\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.*|xfs|lustre\",mountpoint !~\".*pod.*\"})))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sort_desc(100-(avg(rate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\"}[$interval])) by (job) * 100))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Containers per Node",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sort_desc(count(container_memory_rss{job=~\"$cadvisor\",container_label_com_docker_swarm_task_name=~\".+\"}) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Containers per Service",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 6, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sort_desc(count(count(container_memory_rss{job=~\"$cadvisor\",container_label_com_docker_swarm_task_name=~\".+\"}) by (name,container_label_com_docker_swarm_service_name)) by (container_label_com_docker_swarm_service_name))",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Service OOMs",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 20 },
   "targets": [
    {
     "expr": "max(container_memory_failcnt{job=~\"$cadvisor\",container_label_com_docker_swarm_task_name=~\".+\"}) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  }
 ]
}