{
 "title": "Kafka Cluster",
 "description": "Kafka resource usage and throughput",
 "tags": [
  "kafka",
  "support"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": { "query": "label_values(env)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_server_kafkaserver_brokerstate{env=\"${env}\"}, instance)"
    }
   },
   { "name": "percentile", "label": "Percentile", "query": { "query": "label_values(quantile)" } }
  ]
 },
 "panels": [
  { "title": "Healthcheck", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Controllers",
   "type": "stat",
   "description": "Number of active controllers in the cluster.\n\nThis should always be `1`.\n\nIf the controller broker goes down, another broker will be elected as controller.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"} > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Brokers Online",
   "type": "stat",
   "description": "Number of Brokers Online.\n\nThis should be `3`.\n\nWe can live with 1 broker going down.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "description": "Partitions that are online",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Preferred Replica Imbalance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_preferredreplicaimbalancecount{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Broker network throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesinpersec{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\",topic!=\"\"}[5m]))",
     "legendFormat": "Bytes in"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesoutpersec{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\",topic!=\"\"}[5m]))",
     "legendFormat": "Bytes out"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).\n\nThis measurement gives a count of the number of partitions for which the broker is the leader replica, where the follower replicas are not caught up.\n\nGenerally, a steady number of under-replicated partitions ( > 0), indicates that a broker is offline. \n\nIf the number of under replicated partitions is fluctuating, this indicates a performance issue within the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Under Min ISR Partitions",
   "type": "stat",
   "description": "Number of partitions under min insync replicas.\n\nNote, when creating a topic we specified the minimum number of in-sync replicas (`2`).\n\nBy default, each partition should have 3 ISR (each replica will exist on `broker 501`, `broker 502`, `broker 503`). \n\nWe can therefore tolerate one broker / ISR replica going down before producers/consumers wont be able to publish/pull from kafka.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "stat",
   "description": "Number of partitions that dont have an active leader and are hence not writable or readable.\n\nIndicative that a broker may be down!",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate",
   "type": "stat",
   "description": "Unclean leader election rate",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_controllerstats_uncleanleaderelectionspersec{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "Kafka Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Errors that appear in the kafka docker logs will show here. \n\nSome errors are not as serious as others... i.e. there are `RETRIABLE` errors that should resolve themselves depending on our producer/consumers retry rate.\n\nSee: https://kafka.apache.org/20/protocol.html#protocol_error_codes.\n\n`BROKER_NOT_AVAILABLE  |  REPLICA_NOT_AVAILABLE` - These errors are indicators that a broker might not be available. Please go and ensure all brokers are up and running. Note, we some redundancy in that we can support one broker going down from the broker. If we lost another broker (total: 2) we would suffer data-loss as each topic is expected to have at least 2 copies across the cluster. **Severity: high**\n\n`MEMBER_ID_REQUIRED` - consumers need to have an ID before joining a group. All consumers within MRP have a group ID. Thus,  this error should not appear. Regardless, this is more an issue with the consumer logic than broker. **Severity**: **low**\n\n`NOT_CONTROLLER` - This is not the correct controller for this cluster. It may appear on topic creation if not connected to the controller broker.  **Severity: low**\n\n`REBALANCE_IN_PROGRESS` - Whenever a consumer dies/leaves a group, kafka will trigger a **rebalance** which will redistribute partitions to another consumer. Rebalances happen quite regularly in Kafka - deeper look needed if there are 10's of rebalances daily  (and no production deploys).  **Severity: low** (*if there are less than 10 rebalances happening daily*) ... **Severity: high** (*if kafka logs are being spammed with rebalance messages*)\n\n`UNKNOWN*` - Can ignore  this group of errors for now (*red-herrings*) **Severity: low**\n\n`UNKNOWN_TOPIC_OR_PARTITION`. This exception occurs when a producer or consumer  is trying to send/read from a topic/partition that does not exist. Please go and check that the topic exists in the cluster. A ticket should've been raised to create said topic before any changes that use this topic made it to prod. **Severity: high**",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_errorspersec{error!=\"NONE\"}[5m])",
     "legendFormat": "{{error}} @ {{instance}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage of our kafka containers",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"}[5m])*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_max{job=\"kafka-broker\",area=\"heap\",env=\"$env\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Logs size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Log size per Topic",
   "type": "timeseries",
   "description": "Shows the size **on disk** that each topic uses.\n\nIf a topic's log size is growing aggressively, modify the `retention.ms` time of the topic.\n\nWe have ~ `250GB` of disk space per broker. If disk utilization creeps over 200GB, look to purge.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Log size per Broker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Topic counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "PXForms: 1 min",
   "type": "stat",
   "description": "Estimated number of messages that came within the last minute",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"PXForms\"}[1m])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "CEInputURL: 1 min",
   "type": "stat",
   "description": "Estimated number of messages that came within the last minute",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"CEInputURL\"}[1m])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "CETopicScoreURL: 1 min",
   "type": "stat",
   "description": "Estimated number of messages that came within the last minute",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"CETopicScoreURL\"}[1m])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "CEUrlsFailed:  1 min",
   "type": "stat",
   "description": "Estimated number of messages that came within the last minute",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"CEUrlsFailed\"}[1m])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "PXSystemEvents:  1 min",
   "type": "stat",
   "description": "Estimated number of messages that came within the last minute",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"PXSystemEvents\"}[1m])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "PXExportNotifications: 1 min",
   "type": "stat",
   "description": "Estimated number of messages that came within the last minute",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"PXExportNotifications\"}[1m])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "PXBuildRequest: 1 min",
   "type": "stat",
   "description": "Estimated number of messages that came within the last minute",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"PXBuildRequest\"}[1m])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "PXForms: Daily",
   "type": "stat",
   "description": "Estimated number of messages that came within the last minute",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"PXForms\"}[1d])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "CEInputURL: Daily",
   "type": "stat",
   "description": "Estimated number of messages that came within the last minute",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"CEInputURL\"}[1d])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "PXForms: 5 mins",
   "type": "stat",
   "description": "Estimated number of messages that came within the last 5 mins",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"PXForms\"}[5m])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "CEInputURL:  5 mins",
   "type": "stat",
   "description": "Estimated number of messages that came within the last 5 mins",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"CEInputURL\"}[5m])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "CETopicScoreURL:  5 mins",
   "type": "stat",
   "description": "Estimated number of messages that came within the last 5 mins",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"CETopicScoreURL\"}[5m])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "CEUrlsFailed:  5 mins",
   "type": "stat",
   "description": "Estimated number of messages that came within the last 5 mins",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"CEUrlsFailed\"}[5m])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "PXSystemEvents: 5 mins",
   "type": "stat",
   "description": "Estimated number of messages that came within the last 5 mins",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"PXSystemEvents\"}[5m])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "PXExportNotifications:  5 mins",
   "type": "stat",
   "description": "Estimated number of messages that came within the last 5 mins",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"PXExportNotifications\"}[5m])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "PXBuildRequest: 5 mins",
   "type": "stat",
   "description": "Estimated number of messages that came within the last 5 mins",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"PXBuildRequest\"}[5m])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "CETopicScoreURL: Daily",
   "type": "stat",
   "description": "Estimated number of messages that came within the last minute",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"CETopicScoreURL\"}[1d])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "PXForms:  60 mins",
   "type": "stat",
   "description": "Estimated number of messages that came within the last 60 mins",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"PXForms\"}[60m])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "CEInputURL: 60 mins",
   "type": "stat",
   "description": "Estimated number of messages that came within the last 60 mins",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"CEInputURL\"}[60m])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "CETopicScoreURL:  60 mins",
   "type": "stat",
   "description": "Estimated number of messages that came within the last 60 mins",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"CETopicScoreURL\"}[60m])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "CEUrlsFailed:  60 mins",
   "type": "stat",
   "description": "Estimated number of messages that came within the last 60 mins",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"CEUrlsFailed\"}[60m])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "PXSystemEvents:  60 mins",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"PXSystemEvents\"}[60m])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "PXExportNotifications:  60 mins",
   "type": "stat",
   "description": "Estimated number of messages that came within the last 60 mins",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"PXExportNotifications\"}[60m])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "PXBuildRequest: 60 mins",
   "type": "stat",
   "description": "Estimated number of messages that came within the last 60 mins",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"PXBuildRequest\"}[60m])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "CEUrlsFailed: Daily",
   "type": "stat",
   "description": "Estimated number of messages that came within the last minute",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",topic=\"CEUrlsFailed\"}[1d])))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  { "title": "Request rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "All Request Per Sec",
   "type": "stat",
   "description": "Produce request rate.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestspersec{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Produce Request Per Sec",
   "type": "stat",
   "description": "Produce request rate.",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestspersec{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\",request=\"Produce\"}[5m]))"
    }
   ]
  },
  {
   "title": "Consumer Fetch Request Per Sec",
   "type": "stat",
   "description": "Fetch request rate.",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestspersec{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\",request=\"FetchConsumer\"}[5m]))"
    }
   ]
  },
  {
   "title": "Broker Fetch Request Per Sec",
   "type": "stat",
   "description": "Fetch request rate.",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestspersec{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\",request=\"Fetch\"}[5m]))"
    }
   ]
  },
  {
   "title": "Offset Commit Request Per Sec",
   "type": "stat",
   "description": "Offset Commit request rate.",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestspersec{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\",request=\"OffsetCommit\"}[5m]))"
    }
   ]
  },
  {
   "title": "Metadata Request Per Sec",
   "type": "stat",
   "description": "Metadata request rate.",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestspersec{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\",request=\"Metadata\"}[5m]))"
    }
   ]
  },
  {
   "title": "Throughput In/Out",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages In",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum without(instance,topic)(rate(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",env=\"$env\",topic!=\"\"}[5m]))",
       "legendFormat": "bytes/sec"
      }
     ]
    },
    {
     "title": "Bytes In",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum without(instance,topic)(rate(kafka_server_brokertopicmetrics_bytesinpersec{job=\"kafka-broker\",env=\"$env\",topic!=\"\"}[5m]))",
       "legendFormat": "bytes/sec"
      }
     ]
    },
    {
     "title": "Bytes Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum without(instance,topic)(rate(kafka_server_brokertopicmetrics_bytesoutpersec{job=\"kafka-broker\",env=\"$env\",topic!=\"\"}[5m]))",
       "legendFormat": "bytes/sec"
      }
     ]
    },
    {
     "title": "Messages In Per Broker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum without(topic)(rate(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\",topic!=\"\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Bytes In Per Broker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum without(topic)(rate(kafka_server_brokertopicmetrics_bytesinpersec{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\",topic!=\"\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Bytes Out Per Broker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum without(topic)(rate(kafka_server_brokertopicmetrics_bytesoutpersec{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\",topic!=\"\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Processor Avg Usage Percent",
     "type": "timeseries",
     "description": "Average fraction of time the network processor threads are idle. Values are between 0 (all resources are used) and 100 (all resources are available)\n",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1-kafka_network_socketserver_networkprocessoravgidlepercent{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Request Handler Avg Percent",
     "type": "timeseries",
     "description": "Average fraction of time the request handler threads are idle. Values are between 0 (all resources are used) and 100 (all resources are available).\n",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent_total{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Zookeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Zookeeper Request Latency",
     "type": "timeseries",
     "description": "Latency in millseconds for ZooKeeper requests from broker.\n",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_server_zookeeperclientmetrics_zookeeperrequestlatencyms{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\",quantile=~\"$percentile\"}",
       "legendFormat": "{{instance}} - {{quantile}}"
      }
     ]
    },
    {
     "title": "Zookeeper connections per sec",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_server_sessionexpirelistener_zookeepersyncconnectspersec{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Zookeeper expired connections per sec",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_server_sessionexpirelistener_zookeeperexpirespersec{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Zookeeper disconnect per sec",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_server_sessionexpirelistener_zookeeperdisconnectspersec{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Zookeeper auth failures per sec",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_server_sessionexpirelistener_zookeeperauthfailurespersec{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Isr Shrinks / Expands",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "IsrShrinks per Sec",
     "type": "timeseries",
     "description": ": The number of in-sync replicas (ISRs) for a particular partition should remain fairly static, the only exceptions are when you are expanding your broker cluster or removing partitions. In order to maintain high availability, a healthy Kafka cluster requires a minimum number of ISRs for failover. A replica could be removed from the ISR pool for a couple of reasons: it is too far behind the leaders offset (user-configurable by setting the replica.lag.max.messages configuration parameter), or it has not contacted the leader for some time (configurable with the replica.socket.timeout.ms parameter). No matter the reason, an increase in IsrShrinksPerSec without a corresponding increase in IsrExpandsPerSec shortly thereafter is cause for concern and requires user intervention.The Kafka documentation provides a wealth of information on the user-configurable parameters for brokers.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(kafka_server_replicamanager_isrshrinkspersec{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IsrExpands per Sec",
     "type": "timeseries",
     "description": ": The number of in-sync replicas (ISRs) for a particular partition should remain fairly static, the only exceptions are when you are expanding your broker cluster or removing partitions. In order to maintain high availability, a healthy Kafka cluster requires a minimum number of ISRs for failover. A replica could be removed from the ISR pool for a couple of reasons: it is too far behind the leaders offset (user-configurable by setting the replica.lag.max.messages configuration parameter), or it has not contacted the leader for some time (configurable with the replica.socket.timeout.ms parameter). No matter the reason, an increase in IsrShrinksPerSec without a corresponding increase in IsrExpandsPerSec shortly thereafter is cause for concern and requires user intervention.The Kafka documentation provides a wealth of information on the user-configurable parameters for brokers.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(kafka_server_replicamanager_isrexpandspersec{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Connections count per listener",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_socketservermetrics_connection_count{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\"}) by (listener)",
     "legendFormat": "{{listener}}"
    }
   ]
  },
  {
   "title": "Connections count per broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_socketservermetrics_connection_count{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections creation rate per listener",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_socketservermetrics_connection_creation_rate{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\"}) by (listener)",
     "legendFormat": "{{listener}}"
    }
   ]
  },
  {
   "title": "Connections creation rate per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_socketservermetrics_connection_creation_rate{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections close rate per listener",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_socketservermetrics_connection_close_rate{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\"}) by (listener)",
     "legendFormat": "{{listener}}"
    }
   ]
  },
  {
   "title": "Connections close rate per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_socketservermetrics_connection_close_rate{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Acceptor Blocked Percentage",
   "type": "timeseries",
   "description": "Tracks the amount of time Acceptor is blocked from accepting connections. See KIP-402 for more details.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "kafka_network_acceptor_acceptorblockedpercent{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{listener}}"
    }
   ]
  },
  {
   "title": "Connections per client version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_socketservermetrics_connections{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\"}) by (client_software_name, client_software_version)",
     "legendFormat": "{{client_software_name}} {{client_software_version}}"
    }
   ]
  },
  {
   "title": "Group Coordinator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumer groups number per coordinator",
     "type": "timeseries",
     "description": "Number of consumer groups per group coordinator",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_coordinator_group_groupmetadatamanager_numgroups{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Nb consumer groups per state",
     "type": "timeseries",
     "description": "Number of consumer group per state",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupsstable{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\"})",
       "legendFormat": "stable"
      },
      {
       "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupspreparingrebalance{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\"})",
       "legendFormat": "preparing-rebalance"
      },
      {
       "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupsdead{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\"})",
       "legendFormat": "dead"
      },
      {
       "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupscompletingrebalance{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\"})",
       "legendFormat": "completing-rebalance"
      },
      {
       "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupsempty{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\"})",
       "legendFormat": "empty"
      }
     ]
    }
   ]
  },
  {
   "title": "Message Conversion",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of produced message conversion",
     "type": "timeseries",
     "description": "The number of messages produced converted to match the log.message.format.version.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_producemessageconversionspersec{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"})",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Number of consumed message conversion",
     "type": "timeseries",
     "description": "The number of messages consumed converted at consumer to match the log.message.format.version.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_fetchmessageconversionspersec{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"})",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Client version repartition",
     "type": "piechart",
     "description": "Number of connection per client version",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_server_socketservermetrics_connections{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\"}) by (client_software_name, client_software_version) ",
       "legendFormat": "{{client_software_name}} - {{client_software_version}}"
      }
     ]
    }
   ]
  }
 ]
}